Feat/baysian column pooler
leoTiez/htmresearch pull request #8
Opened 2019-12-04 20:53 UTC by kaikun213

Integrate Bayesian Column Pooler implementation and run experiments.

Still needs to be debugged, output representation stays the same for the convergence-experiment. @kaikun213 Todo

2019-12-05 21:20 UTC, leoTiez commented on htmresearch/algorithms/apical_tiebreak_bayesian_temporal_memory.py
> +      # TODO: Should this be included in the if statement?
Yes you are right. I'm fixing it

2019-12-05 22:33 UTC, leoTiez requested changes

2019-12-05 22:33 UTC, leoTiez commented on htmresearch/algorithms/apical_tiebreak_bayesian_temporal_memory.py
> -    if apicalInput.shape[0] < self.apicalInputSize:
Why is that deleted? Isn't that important for converting an index based input to a value based one?

2019-12-05 22:33 UTC, leoTiez commented on htmresearch/frameworks/layers/l2_l4_inference.py
> +      print("learn", objectName, )
Not necessary to do now but for the next pr when we implement the verbosity flags: That is a typical verbosity output

2019-12-05 22:33 UTC, leoTiez commented on htmresearch/frameworks/layers/l2_l4_inference.py
> +  def getBayesianL2Params(self, inputSize, numInputBits):
Since we have the Bayesian L2 default parameters, do we even overwrite them when passing them in the dict in the main experiment file?

2019-12-09 16:33 UTC, kaikun213 commented on htmresearch/algorithms/apical_tiebreak_bayesian_temporal_memory.py
> -    if apicalInput.shape[0] < self.apicalInputSize:
Probability values passed down from L2

2019-12-09 16:36 UTC, leoTiez approved these changes

2019-12-09 16:36 UTC, merged